blueprint:
  name: Motion-activated Switch with Sun Elevation
  domain: automation
  source_url: https://github.com/tayandenga/ha/home-assistant
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain:
          - binary_sensor
          device_class:
          - motion
          multiple: false
    switch_target:
      name: Switch
      selector:
        target:
          entity:
          - domain:
            - switch
      default: ''
    no_motion_wait:
      name: Wait time
      description: Time to wait until the switch should be turned off.
      default: 120
      selector:
        number:
          min: 0.0
          max: 3600.0
          unit_of_measurement: seconds
          step: 1.0
          mode: slider
    below_elevation:
      name: Below sun elevation
      description: Solar elevation. This is the angle between the sun and the horizon.
        Negative values mean the sun is below the horizon.
      default: 3
      selector:
        number:
          min: -90.0
          max: 90.0
          unit_of_measurement: degrees
          step: 1.0
          mode: slider
mode: restart
max_exceeded: silent
trigger:
  platform: state
  entity_id: !input motion_entity
  from: 'off'
  to: 'on'
variables:
  below_elevation: !input below_elevation
condition:
- '{{ state_attr(''sun.sun'',''elevation'') <= (below_elevation | float)}}'
action:
- service: switch.turn_on
  target: !input switch_target
- wait_for_trigger:
    platform: state
    entity_id: !input motion_entity
    from: 'on'
    to: 'off'
- delay: !input no_motion_wait
- service: switch.turn_off
  target: !input switch_target
